export default {
	USER_LIST: 1,
	TRAINER_LIST: 2,
	ATHLETE_LIST: 3,
	USER_ADD: 4,
	USER_DELETE: 5,
	USER_UPDATE: 6,
	TRAINER_ADD: 7,
	TRAINER_DELETE: 8,
	TRAINER_UPDATE: 9,
	ATHLETE_ADD: 10,
	ATHLETE_DELETE: 11,
	ATHLETE_UPDATE: 12,
	PROGRAM_LIST: 13,
	PROGRAM_EDIT: 14,
	PROGRESS_TRACK: 15,
	EXERCISE_MANAGEMENT: 16
};